# Permalinks
# Parannus3
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Tanssiterapia.fi
tagline:             'Päivi Pylvänäinen - Psykologipalveluja tanssiterapian keinoin'
description:         '<img src="/public/paivi-circle.png" width="90%" /><br><b><h2>Päivi Pylvänäinen</h2></b><br><h3>laillistettu psykologi<br>tanssiterepeutti</h3>'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Päivi Pylvänäinen
  url:               https://tanssiterapia.fi
  email:             paivi@tanssiterapia.fi

# Custom vars
version:             1.0.0
